### ISSUE TITLE
Frontend - SSE implementation

### ISSUE THREAD

**Issue by PatrikG-96** [PatrikG-96/D0020E_Grupp11#5]
### **Details**

- SSE API call is implemented on the /lisiten?user_id=.. route
- Server will send JSON data on this connection, following a set format (described elsewhere?)
- A message from the server on this connection can be viewed as receiving an alert for an alarm in realtime

### **Expected result**
Browser can initiate an SSE connection with the web API backend, and parse the data it receives on this connection

### **Dependencies**

- #12

**Comment by arek-e** [comment]
### Details
Created a hook **useEventSource**, Browser can receive data from the eventStream, just by specifying the eventSource (flask api endpoint : string).

### Todo

- Save the state of the alarms in order to use it in other context like web notifications
- Proper unmounting of component
- Change parameters in api call?

### Bugs
